
const vm = {
_uid: 1,
_isVue: true,
'$options':
    { parent:
    VueComponent {
        _uid: 0,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [VueComponent],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': {},
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: [Object: null prototype] {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: [Object: null prototype] {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
    _parentVnode:
    VNode {
        tag: 'vue-component-3-VueEditor',
        data: [Object],
        children: undefined,
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [VueComponent],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: [Object],
        componentInstance: [Circular],
        parent: undefined,
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
    propsData: { value: 'Vue School newww', editorToolbar: [Array] },
    _parentListeners: {},
    _renderChildren: undefined,
    _componentTag: undefined,
    _propKeys:
    [ 'customModules',
        'id',
        'placeholder',
        'value',
        'disabled',
        'editorToolbar',
        'editorOptions',
        'useCustomImageHandler',
        'useMarkdownShortcuts' ] },
_renderProxy:
    VueComponent {
    _uid: 1,
    _isVue: true,
    '$options':
    { parent: [VueComponent],
        _parentVnode: [VNode],
        propsData: [Object],
        _parentListeners: {},
        _renderChildren: undefined,
        _componentTag: undefined,
        _propKeys: [Array] },
    _renderProxy: [Circular],
    _self: [Circular],
    '$parent':
    VueComponent {
        _uid: 0,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [VueComponent],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': {},
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: [Object: null prototype] {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: [Object: null prototype] {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
    '$root':
    VueComponent {
        _uid: 0,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [VueComponent],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': {},
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: [Object: null prototype] {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: [Object: null prototype] {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
    '$children': [],
    '$refs': { quillContainer: [HTMLDivElement] },
    _watcher:
    Watcher {
        vm: [Circular],
        deep: false,
        user: false,
        lazy: false,
        sync: false,
        before: [Function: before],
        cb: [Function: noop],
        id: 4,
        active: true,
        dirty: false,
        deps: [Array],
        newDeps: [],
        depIds: [Set],
        newDepIds: Set {},
        expression:
        'function () {\n      vm._update(vm._render(), hydrating);\n    }',
        getter: [Function: updateComponent],
        value: undefined },
    _inactive: null,
    _directInactive: false,
    _isMounted: true,
    _isDestroyed: false,
    _isBeingDestroyed: false,
    _events: [Object: null prototype] {},
    _hasHookEvent: false,
    _vnode:
    VNode {
        tag: 'div',
        data: [Object],
        children: [Array],
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [Circular],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: undefined,
        componentInstance: undefined,
        parent: [VNode],
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
    _staticTrees: null,
    '$vnode':
    VNode {
        tag: 'vue-component-3-VueEditor',
        data: [Object],
        children: undefined,
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [VueComponent],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: [Object],
        componentInstance: [Circular],
        parent: undefined,
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
    '$slots': {},
    '$scopedSlots': {},
    _c: [Function: createElement],
    '$createElement': [Function: createElement],
    '$attrs': [Getter/Setter],
    '$listeners': [Getter/Setter],
    __emitted: [Object: null prototype] { ready: [Array] },
    __emittedByOrder: [ [Object] ],
    '$emit': [Function],
    _watchers: [ [Watcher], [Watcher], [Watcher] ],
    _props:
    { customModules: [Getter/Setter],
        id: [Getter/Setter],
        placeholder: [Getter/Setter],
        value: [Getter/Setter],
        disabled: [Getter/Setter],
        editorToolbar: [Getter/Setter],
        editorOptions: [Getter/Setter],
        useCustomImageHandler: [Getter/Setter],
        useMarkdownShortcuts: [Getter/Setter] },
    registerCustomModules: [Function: bound registerCustomModules],
    initializeEditor: [Function: bound initializeEditor],
    setupQuillEditor: [Function: bound setupQuillEditor],
    setModules: [Function: bound setModules],
    prepareEditorConfig: [Function: bound prepareEditorConfig],
    registerPrototypes: [Function: bound registerPrototypes],
    registerEditorEventListeners: [Function: bound registerEditorEventListeners],
    listenForEditorEvent: [Function: bound listenForEditorEvent],
    handleInitialContent: [Function: bound handleInitialContent],
    handleSelectionChange: [Function: bound handleSelectionChange],
    handleTextChange: [Function: bound handleTextChange],
    checkForCustomImageHandler: [Function: bound checkForCustomImageHandler],
    setupCustomImageHandler: [Function: bound setupCustomImageHandler],
    customImageHandler: [Function: bound customImageHandler],
    emitImageInfo: [Function: bound emitImageInfo],
    _data: { quill: [Getter/Setter] },
    quill: [Getter/Setter],
    '$el':
    HTMLDivElement { _prevClass: 'quillWrapper', __vue__: [VueComponent] } },
_self: [Circular],
'$parent':
    VueComponent {
    _uid: 0,
    _isVue: true,
    '$options':
    { components: [Object],
        directives: {},
        filters: {},
        _base: [Function],
        _Ctor: [Object],
        beforeCreate: [Array],
        provide: [Function: mergedInstanceDataFn],
        '$_doNotStubChildren': true,
        _isFunctionalContainer: undefined,
        render: [Function] },
    _renderProxy:
    VueComponent {
        _uid: 0,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [Circular],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': {},
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: [Object: null prototype] {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: [Object: null prototype] {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
    _self: [Circular],
    '$parent': undefined,
    '$root': [Circular],
    '$children': [ [Circular] ],
    '$refs': {},
    _watcher:
    Watcher {
        vm: [Circular],
        deep: false,
        user: false,
        lazy: false,
        sync: false,
        before: [Function: before],
        cb: [Function: noop],
        id: 1,
        active: true,
        dirty: false,
        deps: [],
        newDeps: [],
        depIds: Set {},
        newDepIds: Set {},
        expression:
        'function () {\n      vm._update(vm._render(), hydrating);\n    }',
        getter: [Function: updateComponent],
        value: undefined },
    _inactive: null,
    _directInactive: false,
    _isMounted: true,
    _isDestroyed: false,
    _isBeingDestroyed: false,
    _events: [Object: null prototype] {},
    _hasHookEvent: false,
    _vnode:
    VNode {
        tag: 'vue-component-3-VueEditor',
        data: [Object],
        children: undefined,
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [Circular],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: [Object],
        componentInstance: [Circular],
        parent: undefined,
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
    _staticTrees: null,
    '$vnode': undefined,
    '$slots': {},
    '$scopedSlots': {},
    _c: [Function],
    '$createElement': [Function],
    '$attrs': [Getter/Setter],
    '$listeners': [Getter/Setter],
    __emitted: [Object: null prototype] {},
    __emittedByOrder: [],
    '$emit': [Function],
    _watchers: [ [Watcher] ],
    _data: {},
    _provided: undefined,
    '$el':
    HTMLDivElement { _prevClass: 'quillWrapper', __vue__: [Circular] } },
'$root':
    VueComponent {
    _uid: 0,
    _isVue: true,
    '$options':
    { components: [Object],
        directives: {},
        filters: {},
        _base: [Function],
        _Ctor: [Object],
        beforeCreate: [Array],
        provide: [Function: mergedInstanceDataFn],
        '$_doNotStubChildren': true,
        _isFunctionalContainer: undefined,
        render: [Function] },
    _renderProxy:
    VueComponent {
        _uid: 0,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [Circular],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': {},
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: [Object: null prototype] {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: [Object: null prototype] {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
    _self: [Circular],
    '$parent': undefined,
    '$root': [Circular],
    '$children': [ [Circular] ],
    '$refs': {},
    _watcher:
    Watcher {
        vm: [Circular],
        deep: false,
        user: false,
        lazy: false,
        sync: false,
        before: [Function: before],
        cb: [Function: noop],
        id: 1,
        active: true,
        dirty: false,
        deps: [],
        newDeps: [],
        depIds: Set {},
        newDepIds: Set {},
        expression:
        'function () {\n      vm._update(vm._render(), hydrating);\n    }',
        getter: [Function: updateComponent],
        value: undefined },
    _inactive: null,
    _directInactive: false,
    _isMounted: true,
    _isDestroyed: false,
    _isBeingDestroyed: false,
    _events: [Object: null prototype] {},
    _hasHookEvent: false,
    _vnode:
    VNode {
        tag: 'vue-component-3-VueEditor',
        data: [Object],
        children: undefined,
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [Circular],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: [Object],
        componentInstance: [Circular],
        parent: undefined,
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
    _staticTrees: null,
    '$vnode': undefined,
    '$slots': {},
    '$scopedSlots': {},
    _c: [Function],
    '$createElement': [Function],
    '$attrs': [Getter/Setter],
    '$listeners': [Getter/Setter],
    __emitted: [Object: null prototype] {},
    __emittedByOrder: [],
    '$emit': [Function],
    _watchers: [ [Watcher] ],
    _data: {},
    _provided: undefined,
    '$el':
    HTMLDivElement { _prevClass: 'quillWrapper', __vue__: [Circular] } },
'$children': [],
'$refs':
    { quillContainer:
    HTMLDivElement { __quill: [Quill], [Symbol(SameObject caches)]: [Object] } },
_watcher:
    Watcher {
    vm: [Circular],
    deep: false,
    user: false,
    lazy: false,
    sync: false,
    before: [Function: before],
    cb: [Function: noop],
    id: 4,
    active: true,
    dirty: false,
    deps: [ [Dep], [Dep] ],
    newDeps: [],
    depIds: Set { 6, 13 },
    newDepIds: Set {},
    expression:
    'function () {\n      vm._update(vm._render(), hydrating);\n    }',
    getter: [Function: updateComponent],
    value: undefined },
_inactive: null,
_directInactive: false,
_isMounted: true,
_isDestroyed: false,
_isBeingDestroyed: false,
_events: [Object: null prototype] {},
_hasHookEvent: false,
_vnode:
    VNode {
    tag: 'div',
    data: { staticClass: 'quillWrapper' },
    children: [ [VNode], [VNode], [VNode], [VNode] ],
    text: undefined,
    elm:
    HTMLDivElement { _prevClass: 'quillWrapper', __vue__: [VueComponent] },
    ns: undefined,
    context: [Circular],
    fnContext: undefined,
    fnOptions: undefined,
    fnScopeId: undefined,
    key: undefined,
    componentOptions: undefined,
    componentInstance: undefined,
    parent:
    VNode {
        tag: 'vue-component-3-VueEditor',
        data: [Object],
        children: undefined,
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [VueComponent],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: [Object],
        componentInstance: [Circular],
        parent: undefined,
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
    raw: false,
    isStatic: false,
    isRootInsert: true,
    isComment: false,
    isCloned: false,
    isOnce: false,
    asyncFactory: undefined,
    asyncMeta: undefined,
    isAsyncPlaceholder: false },
_staticTrees: null,
'$vnode':
    VNode {
    tag: 'vue-component-3-VueEditor',
    data:
    { attrs: {},
        on: undefined,
        scopedSlots: [Object],
        hook: [Object],
        pendingInsert: null },
    children: undefined,
    text: undefined,
    elm:
    HTMLDivElement { _prevClass: 'quillWrapper', __vue__: [VueComponent] },
    ns: undefined,
    context:
    VueComponent {
        _uid: 0,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [VueComponent],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': {},
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: [Object: null prototype] {},
        _hasHookEvent: false,
        _vnode: [Circular],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: [Object: null prototype] {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
    fnContext: undefined,
    fnOptions: undefined,
    fnScopeId: undefined,
    key: undefined,
    componentOptions:
    { Ctor: [Function],
        propsData: [Object],
        listeners: {},
        tag: undefined,
        children: undefined },
    componentInstance: [Circular],
    parent: undefined,
    raw: false,
    isStatic: false,
    isRootInsert: true,
    isComment: false,
    isCloned: false,
    isOnce: false,
    asyncFactory: undefined,
    asyncMeta: undefined,
    isAsyncPlaceholder: false },
'$slots': {},
'$scopedSlots': {},
_c: [Function: createElement],
'$createElement': [Function: createElement],
'$attrs': [Getter/Setter],
'$listeners': [Getter/Setter],
__emitted: [Object: null prototype] { ready: [ [Array] ] },
__emittedByOrder: [ { name: 'ready', args: [Array] } ],
'$emit': [Function],
_watchers:
    [ Watcher {
        vm: [Circular],
        deep: false,
        user: true,
        lazy: false,
        sync: false,
        before: undefined,
        cb: [Function: value],
        id: 2,
        active: true,
        dirty: false,
        deps: [Array],
        newDeps: [],
        depIds: [Set],
        newDepIds: Set {},
        expression: 'value',
        getter: [Function],
        value: 'Vue School newww' },
    Watcher {
        vm: [Circular],
        deep: false,
        user: true,
        lazy: false,
        sync: false,
        before: undefined,
        cb: [Function: disabled],
        id: 3,
        active: true,
        dirty: false,
        deps: [Array],
        newDeps: [],
        depIds: [Set],
        newDepIds: Set {},
        expression: 'disabled',
        getter: [Function],
        value: false },
    Watcher {
        vm: [Circular],
        deep: false,
        user: false,
        lazy: false,
        sync: false,
        before: [Function: before],
        cb: [Function: noop],
        id: 4,
        active: true,
        dirty: false,
        deps: [Array],
        newDeps: [],
        depIds: [Set],
        newDepIds: Set {},
        expression:
        'function () {\n      vm._update(vm._render(), hydrating);\n    }',
        getter: [Function: updateComponent],
        value: undefined } ],
_props:
    { customModules: [Getter/Setter],
    id: [Getter/Setter],
    placeholder: [Getter/Setter],
    value: [Getter/Setter],
    disabled: [Getter/Setter],
    editorToolbar: [Getter/Setter],
    editorOptions: [Getter/Setter],
    useCustomImageHandler: [Getter/Setter],
    useMarkdownShortcuts: [Getter/Setter] },
registerCustomModules: [Function: bound registerCustomModules],
initializeEditor: [Function: bound initializeEditor],
setupQuillEditor: [Function: bound setupQuillEditor],
setModules: [Function: bound setModules],
prepareEditorConfig: [Function: bound prepareEditorConfig],
registerPrototypes: [Function: bound registerPrototypes],
registerEditorEventListeners: [Function: bound registerEditorEventListeners],
listenForEditorEvent: [Function: bound listenForEditorEvent],
handleInitialContent: [Function: bound handleInitialContent],
handleSelectionChange: [Function: bound handleSelectionChange],
handleTextChange: [Function: bound handleTextChange],
checkForCustomImageHandler: [Function: bound checkForCustomImageHandler],
setupCustomImageHandler: [Function: bound setupCustomImageHandler],
customImageHandler: [Function: bound customImageHandler],
emitImageInfo: [Function: bound emitImageInfo],
_data: { quill: [Getter/Setter] },
quill: [Getter/Setter],
'$el':
    HTMLDivElement {
    _prevClass: 'quillWrapper',
    __vue__:
    VueComponent {
        _uid: 0,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [VueComponent],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': {},
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: [Object: null prototype] {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: [Object: null prototype] {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [Circular] } } }
